name: github-get-secrets-from-azure-kv-and-configure-as-repo-secrets
on:
  workflow_dispatch:
    inputs:
      keyvault_name:
        required: true
        type: string
        description: 'key vault name'
        default: ''
      repo_search_string:
        required: true
        type: string
        description: 'github repo name search string'
        default: ''

jobs:
  github-get-secrets-from-azure-kv-and-configure-as-repo-secrets:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: package installations
        run: |
          pip install poetry
          poetry install

      - name: Token generator
        uses: githubofkrishnadhas/github-access-using-githubapp@v1
        with:
          github_app_id: ${{ secrets.TOKEN_GENERATOR_APPID }}
          github_app_private_key : ${{ secrets.TOKEN_GENERATOR_PRIVATE_KEY }}
          github_account_type : 'organization'

      - name: run python program
        run: |
          poetry run python3 main.py --keyvault_name ${{ github.event.inputs.keyvault_name }} \
                                        --repo_search_string ${{ github.event.inputs.repo_search_string }}
      - name: job completed
        run: echo "Job is completed"

